[project]
name = "video-splitter"
version = "0.2.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "customtkinter>=5.2.2",
    "opencv-python>=4.12.0.88",
    "pillow>=12.0.0",
]
